# Path related
# Reads from *_feature if extract_online is False
# training_feature: manifest/training_feat.txt
# validation_feature: manifest/validation_feat.txt

# Reads from *_meta if extract_online is True
training_meta: manifest/training.txt
validation_meta: manifest/validation.txt

class_ids: manifest/class_ids.json
checkpoint: null # will keep training if not `null`
save_path: saved_model

# dataloader
train:
    num_workers: 12
    batch_size: 256
val:
    num_workers: 12
    batch_size: 512

# network
num_epochs: 50
save_epoch: 5 # always saves the best checkpoint despite how this number is set
extract_online: True

# spectrogram
spectrogram:
    type: linear # linear or mel
    n_fft: 512 # used when type == linear
    n_mels: 256 # used when type == mel
    min_dur_sec: 5 # will pad every sequence to this length
    sample_sec: 5 # this should not be bigger than min_dur_sec

feature: !new:torchaudio.transforms.Spectrogram
    n_fft: !ref <spectrogram[n_fft]>
    win_length: 400
    hop_length: 160
    power: 1
    normalized: window # window or frame_length

# timemasking: !new:torchaudio.transforms.TimeMasking
#     time_mask_param: !ref <spectrogram[sample_sec]> * 16000 // 4
#     p: 0.5

# freqmasking: !new:torchaudio.transforms.FrequencyMasking
#     freq_mask_param: !ref <spectrogram[n_fft]> // 8

transforms:
    names: 
        - feature
        # - time_masking
        # - freq_masking
    modules:
        - !ref <feature>
        # - !ref <timemasking>
        # - !ref <freqmasking>

# optimizer
optimizer: !name:torch.optim.Adam
    lr: 0.001
    weight_decay: 0.000002
    betas: (0.9, 0.98)
    eps: 1e-9