# Path related
# Reads from *_feature if extract_online is False
training_feature: manifest/training_feat.txt
validation_feature: manifest/validation_feat.txt
# Reads from *_meta if extract_online is True
training_meta: manifest/training.txt
validation_meta: manifest/validation.txt
save_path: ./saved_model

# Configuration
input_dim: 257
num_classes: 7
batch_size: 256
sample_sec: 5
num_epochs: 50
save_epoch: 5
extract_online: True