# Path related
# Reads from *_feature if extract_online is False
training_feature: meta_7lang/training_feat.txt
validation_feature: meta_7lang/validation_feat.txt
# Reads from *_meta if extract_online is True
training_meta: meta_7lang/training.txt
validation_meta: meta_7lang/validation.txt
save_path: ./saved_model

# Configuration
input_dim: 257
num_classes: 14
batch_size: 512
sample_sec: 5
num_epochs: 10
save_epoch: 1
extract_online: True