# Path related
# Reads from *_feature if extract_online is False
# training_feature: manifest/training_feat.txt
# validation_feature: manifest/validation_feat.txt

# Reads from *_meta if extract_online is True
training_meta: manifest/training.txt
validation_meta: manifest/validation.txt

class_ids: manifest/class_ids.json
checkpoint: null # will keep training if not `null`
save_path: saved_model

# dataloader
train:
    num_workers: 12
    batch_size: 256
val:
    num_workers: 12
    batch_size: 512

# network
num_epochs: 50
save_epoch: 5 # always saves the best checkpoint despite how this number is set
extract_online: True

# spectrogram
spectrogram:
    spec_sec: 4 # make this smaller if the error says "high<0", max=10 should work with VoxCentum
    n_fft: 512
    win_length: 400
    hop_length: 160

# optimizer
optimizer: !name:torch.optim.Adam
    lr: 0.001
    weight_decay: 0.000002
    betas: (0.9, 0.98)
    eps: 1e-9